#+TITLE: FIXME: Inside Emacs 6 part 4
#+AUTHOR: Tony Aldon
#+DATE: <2021-08-05 Thu>
#+PROPERTY: YOUTUBE_LINK  https://youtu.be/0fbrVArRxUo
#+PROPERTY: CONFIG_REPO   https://github.com/tonyaldon/emacs.d
#+PROPERTY: CONFIG_COMMIT 124a1958e4e222722980ced00724f0ee7c948575
#+PROPERTY: VIDEO_SCR_DIR ../src/inside-emacs-06-part-04/
#+TAGS: FIXME

* Description

* Commands
** built-in
*** global-map

~undo~ (~C-x u~): Undo some previous changes.

*** org-mode-map

~org-ctrl-c-ctrl-c~ (~C-c C-c~): Set tags in headline, or update according
to changed information at point.

~org-ctrl-c-minus~ (~C-c -~): Insert separator line in table or modify
bullet status of line.

~org-ctrl-c-ret~ (~C-c RET~): Call ~org-table-hline-and-move~ or
~org-insert-heading~.

~org-cycle~ (~TAB~): TAB-action and visibility cycling for Org mode.

~org-forward-sentence~ (~M-e~): Go to end of sentence, or end of table
field.

~org-return~ (~RET~): Goto next table row or insert a newline.

~org-shiftmetaright~ (~M-S-<right>~): Demote subtree or insert table
column.

~org-shifttab~ (~S-TAB~): Global visibility cycling or move to previous
table field.

~org-sort~ (~C-c ^~): Call ~org-sort-entries~, ~org-table-sort-lines~ or
~org-sort-list~.

~org-table-hline-and-move~ (~C-c RET~): Insert a hline and move to the row
below that line.

*** org-mode

~org-table-copy-region~: Copy rectangular region in table to clipboard.

~org-table-paste-rectangle~: Paste a rectangular region into a table.

** external

~avy-goto-char~ (from [[https://github.com/abo-abo/avy][avy]]): Jump to the currently visible char (read in
the minibuffer).

** customized
